import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import classes.MetodosUtilitarios;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pichau
 */
public class Login extends javax.swing.JFrame {

    ClasseConexaoJava con;
    String output = "";
    String nome_adm = "";
    public static String SetLoginName;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIcon();
        
    }
        
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bemvindo = new javax.swing.JLabel();
        Faca = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta");
        setMinimumSize(new java.awt.Dimension(500, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        Bemvindo.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        Bemvindo.setForeground(new java.awt.Color(255, 255, 255));
        Bemvindo.setText("Bem-vindo");
        getContentPane().add(Bemvindo);
        Bemvindo.setBounds(150, 40, 190, 60);

        Faca.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        Faca.setForeground(new java.awt.Color(163, 186, 255));
        Faca.setText("Faça login para acessar a consulta");
        getContentPane().add(Faca);
        Faca.setBounds(90, 100, 320, 30);

        Login.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        Login.setForeground(new java.awt.Color(191, 207, 255));
        Login.setText("LOGIN");
        getContentPane().add(Login);
        Login.setBounds(50, 150, 70, 30);

        lblSenha.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(191, 207, 255));
        lblSenha.setText("SENHA");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(50, 240, 60, 22);

        txtLogin.setBackground(new java.awt.Color(44, 70, 150));
        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 35, 79)));
        txtLogin.setPreferredSize(new java.awt.Dimension(2, 18));
        getContentPane().add(txtLogin);
        txtLogin.setBounds(50, 180, 390, 40);

        txtSenha.setBackground(new java.awt.Color(44, 70, 150));
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 35, 79)));
        getContentPane().add(txtSenha);
        txtSenha.setBounds(50, 270, 390, 40);

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(52, 85, 185));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(50, 340, 390, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemfundo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        con = new ClasseConexaoJava();
        boolean resultado = con.conectar();
        if(resultado == true){
            try{
                String query = "select senha, nome from ADM where login_adm=?";
                PreparedStatement pst = con.getConn().prepareStatement(query);
                pst.setString(1, txtLogin.getText());
                
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    output = rs.getString("senha");
                    nome_adm = rs.getString("nome");
                }
            }
            catch (Exception erro){
                JOptionPane.showMessageDialog(null, erro);
            }
            
            if(txtSenha.getText().equals(output.replace(" ", ""))){    
                SetLoginName = txtLogin.getText();
                new jfPaginaInicial().setVisible(true);
                this.setVisible(false);
                dispose();
                
           
            } else {
                JOptionPane.showMessageDialog(null, "Login ou senha incorreto!");
            }
            
            
        }
        
        
        
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    
    
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bemvindo;
    private javax.swing.JLabel Faca;
    private javax.swing.JLabel Login;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
